# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Biscuits, GDPR & Cookie Banner"
client_id = "fc7bdfa96b7f797704c7b962cf263b29"
application_url = "https://vitamins-postcard-ds-db.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://vitamins-postcard-ds-db.trycloudflare.com/auth/callback",
  "https://vitamins-postcard-ds-db.trycloudflare.com/auth/shopify/callback",
  "https://vitamins-postcard-ds-db.trycloudflare.com/api/auth/callback",
  "https://vitamins-postcard-ds-db.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://prefer-variables-nj-championship.trycloudflare.com/webhooks"
  customer_data_request_url = "https://prefer-variables-nj-championship.trycloudflare.com/webhooks"
  shop_deletion_url = "https://prefer-variables-nj-championship.trycloudflare.com/webhooks"

[app_proxy]
url = "https://vitamins-postcard-ds-db.trycloudflare.com"
subpath = "cookie_ray_sma_fa"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-farid-2.myshopify.com"
