# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "banner-admin"
client_id = "37df1e843ea819cd5d87d3860a9835bd"
application_url = "https://leo-shipped-christina-mat.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://leo-shipped-christina-mat.trycloudflare.com/auth/callback",
  "https://leo-shipped-christina-mat.trycloudflare.com/auth/shopify/callback",
  "https://leo-shipped-christina-mat.trycloudflare.com/api/auth/callback",
  "https://leo-shipped-christina-mat.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "scan-test.myshopify.com"
