# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "gdpr-app-by-awesoon-inc"
client_id = "fc7bdfa96b7f797704c7b962cf263b29"
application_url = "https://router-progress-charter-tiger.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://router-progress-charter-tiger.trycloudflare.com/auth/callback",
  "https://router-progress-charter-tiger.trycloudflare.com/auth/shopify/callback",
  "https://router-progress-charter-tiger.trycloudflare.com/api/auth/callback",
  "https://router-progress-charter-tiger.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[app_proxy]
url = "https://router-progress-charter-tiger.trycloudflare.com"
subpath = "cookie_ray_sma_fa"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "chatup-demo.myshopify.com"
